#Need to determine the boundary radius here


ros__parameters:

  update_frequency: 5.0

  publish_frequency: 2.0

  global_frame: odom

  robot_base_frame: base_link

  rolling_window: true

  width: 3

  height: 3

  resolution: 0.05

  robot_radius: 0.22

  plugins: ["voxel_layer", "inflation_layer"]

    