global_costmap:
  global_costmap:
    ros__parameters:
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      global_costmap_parameters: !include global_costmap.yaml
      static_layer: !include static_layer.yaml
      obstacle_layer: !include obstacle_layer.yaml
      inflation_layer: !include inflation_layer.yaml

local_costmap:
  local_costmap:
    ros__parameters:
      plugins: ["voxel_layer", "inflation_layer"]
      local_costmap_parameters: !include global_costmap.yaml
      voxel_layer: !include voxel_layer.yaml
      inflation_layer: !include inflation_layer.yaml
