planner_server:
  ros__parameters:
    expected_planner_frequency: 2.0
    use_sim_time: true
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_theta_star_planner/ThetaStarPlanner"
      how_many_corners: 8
      w_euc_cost: 1.0
      w_traversal_cost: 5.0
      w_heuristic_cost: 1.0

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 2.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      transform_tolerance: 0.8
      use_sim_time: true
      robot_radius: 0.38
      footprint_padding: 0.0
      resolution: 0.04
      track_unknown_space: false
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      filters: ["keepout_filter", "filter_inflation"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: /map
        map_subscribe_transient_local: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: false
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 5.0
          raytrace_min_range: 0.0
          obstacle_max_range: 4.5
          obstacle_min_range: 0.15
          inf_is_valid: false
          clearing_threshold: 0.48
          marking_threshold: 0.52

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.3
        inflation_radius: 0.40

      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: true
        filter_info_topic: "/costmap_filter_info"
        override_lethal_cost: true
        lethal_override_cost: 200.0

      filter_inflation:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.25
        cost_scaling_factor: 8.0

      always_send_full_costmap: true
